# Eldritch Theme for Helix Editor
# A dark theme inspired by Lovecraftian horror
# Main repo: https://github.com/eldritch-theme/eldritch.nvim

# UI Elements
"ui.background" = { bg = "bg" }
"ui.background.separator" = { fg = "purple" }
"ui.cursor" = { fg = "bg", bg = "fg" }
"ui.cursor.primary" = { fg = "bg", bg = "fg" }
"ui.cursor.match" = { bg = "visual" }
"ui.cursor.insert" = { fg = "bg", bg = "green" }
"ui.cursor.select" = { fg = "bg", bg = "cyan" }
"ui.cursorline" = { bg = "bg_highlight" }
"ui.linenr" = { fg = "fg_gutter_light" }
"ui.linenr.selected" = { fg = "green", modifiers = ["bold"] }
"ui.statusline" = { fg = "fg", bg = "bg_dark" }
"ui.statusline.inactive" = { fg = "fg_gutter", bg = "bg_dark" }
"ui.statusline.normal" = { fg = "bg", bg = "cyan", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "bg", bg = "green", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "bg", bg = "magenta", modifiers = ["bold"] }
"ui.bufferline" = { fg = "fg_gutter", bg = "bg_dark" }
"ui.bufferline.active" = { fg = "fg", bg = "bg" }
"ui.bufferline.background" = { bg = "bg_dark" }
"ui.popup" = { bg = "bg_dark", fg = "fg" }
"ui.popup.info" = { bg = "bg_dark", fg = "fg" }
"ui.window" = { fg = "purple" }
"ui.help" = { bg = "bg_dark", fg = "fg" }
"ui.text" = { fg = "fg" }
"ui.text.focus" = { fg = "cyan" }
"ui.text.inactive" = { fg = "fg_dark" }
"ui.text.info" = { fg = "fg", bg = "bg_dark" }
"ui.virtual" = { fg = "fg_gutter" }
"ui.virtual.ruler" = { bg = "bg_highlight" }
"ui.virtual.whitespace" = { fg = "fg_gutter" }
"ui.virtual.indent-guide" = { fg = "fg_gutter" }
"ui.virtual.inlay-hint" = { fg = "dark3", bg = "bg_highlight" }
"ui.virtual.jump-label" = { fg = "bg", bg = "magenta2", modifiers = ["bold"] }
"ui.selection" = { bg = "magenta3" }
"ui.selection.primary" = { bg = "visual" }
"ui.highlight" = { bg = "bg_search" }
"ui.menu" = { fg = "fg", bg = "bg_dark" }
"ui.menu.selected" = { fg = "fg", bg = "dark5" }
"ui.menu.scroll" = { fg = "fg_gutter", bg = "bg_dark" }

# Diagnostic
"diagnostic" = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.warning" = { underline = { color = "orange", style = "curl" } }
"diagnostic.info" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.hint" = { underline = { color = "dark_green", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

# Diff
"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "orange" }
"diff.minus" = { fg = "red" }

# Git
"git.added" = { fg = "green" }
"git.modified" = { fg = "comment" }
"git.removed" = { fg = "red" }
"git.delta.moved" = { fg = "cyan" }

# Syntax Highlighting
"comment" = { fg = "comment", modifiers = ["italic"] }
"comment.block" = { fg = "comment", modifiers = ["italic"] }
"comment.line" = { fg = "comment", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "comment", modifiers = ["italic"] }

"constant" = { fg = "red" }
"constant.builtin" = { fg = "bright_cyan" }
"constant.builtin.boolean" = { fg = "green" }
"constant.character" = { fg = "orange" }
"constant.character.escape" = { fg = "magenta" }
"constant.numeric" = { fg = "green" }
"constant.numeric.integer" = { fg = "green" }
"constant.numeric.float" = { fg = "pink" }

"string" = { fg = "yellow" }
"string.regexp" = { fg = "cyan" }
"string.special" = { fg = "yellow" }
"string.special.symbol" = { fg = "green" }
"string.special.url" = { fg = "yellow", modifiers = ["italic", "underlined"] }

"character" = { fg = "pink" }
"character.special" = { fg = "pink" }

"boolean" = { fg = "green" }
"number" = { fg = "green" }
"float" = { fg = "pink" }

"variable" = { fg = "cyan" }
"variable.builtin" = { fg = "red" }
"variable.parameter" = { fg = "purple" }
"variable.other.member" = { fg = "purple" }

"label" = { fg = "cyan" }

"punctuation" = { fg = "cyan" }
"punctuation.bracket" = { fg = "fg_dark" }
"punctuation.delimiter" = { fg = "cyan" }
"punctuation.special" = { fg = "cyan" }

"keyword" = { fg = "green" }
"keyword.control" = { fg = "green" }
"keyword.control.conditional" = { fg = "purple" }
"keyword.control.repeat" = { fg = "purple" }
"keyword.control.import" = { fg = "green" }
"keyword.control.return" = { fg = "green" }
"keyword.control.exception" = { fg = "green" }
"keyword.operator" = { fg = "purple" }
"keyword.directive" = { fg = "dark_cyan" }
"keyword.function" = { fg = "magenta" }
"keyword.storage" = { fg = "purple" }
"keyword.storage.modifier" = { fg = "purple" }
"keyword.storage.type" = { fg = "cyan" }

"operator" = { fg = "cyan" }

"function" = { fg = "pink" }
"function.builtin" = { fg = "cyan" }
"function.method" = { fg = "purple" }
"function.macro" = { fg = "purple" }
"function.special" = { fg = "cyan" }

"constructor" = { fg = "magenta" }

"type" = { fg = "cyan" }
"type.builtin" = { fg = "cyan", modifiers = ["italic"] }
"type.enum" = { fg = "cyan" }
"type.enum.variant" = { fg = "green" }

"property" = { fg = "purple" }
"attribute" = { fg = "cyan" }
"attribute.builtin" = { fg = "cyan" }

"namespace" = { fg = "orange" }
"module" = { fg = "orange" }

"special" = { fg = "cyan" }

"markup.heading" = { fg = "purple", modifiers = ["bold"] }
"markup.heading.1" = { fg = "cyan", modifiers = ["bold"] }
"markup.heading.2" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.3" = { fg = "purple", modifiers = ["bold"] }
"markup.heading.4" = { fg = "cyan", modifiers = ["bold"] }
"markup.heading.5" = { fg = "magenta", modifiers = ["bold"] }
"markup.heading.6" = { fg = "green", modifiers = ["bold"] }
"markup.list" = { fg = "cyan" }
"markup.list.unnumbered" = { fg = "cyan" }
"markup.list.numbered" = { fg = "orange" }
"markup.list.checked" = { fg = "purple" }
"markup.list.unchecked" = { fg = "cyan" }
"markup.bold" = { fg = "orange", modifiers = ["bold"] }
"markup.italic" = { fg = "yellow", modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link" = { fg = "cyan", modifiers = ["bold"] }
"markup.link.url" = { fg = "yellow", modifiers = ["italic", "underlined"] }
"markup.link.label" = { fg = "cyan" }
"markup.link.text" = { fg = "cyan", modifiers = ["underlined"] }
"markup.quote" = { fg = "yellow", modifiers = ["italic"] }
"markup.raw" = { fg = "yellow" }
"markup.raw.inline" = { fg = "cyan", bg = "terminal_black" }
"markup.raw.block" = { fg = "cyan" }

"tag" = { fg = "cyan" }
"tag.builtin" = { fg = "cyan" }
"tag.attribute" = { fg = "pink" }
"tag.delimiter" = { fg = "cyan" }

# Error and Warning
"error" = { fg = "red" }
"warning" = { fg = "orange" }
"info" = { fg = "yellow" }
"hint" = { fg = "dark_green" }

[palette]
# Background colors
bg = "#212337"
bg_dark = "#171928"
bg_highlight = "#292e42"
terminal_black = "#414868"

# Foreground colors
fg = "#ebfafa"
fg_dark = "#ABB4DA"
fg_gutter = "#3b4261"
fg_gutter_light = "#7081d0"

# Color palette
dark3 = "#6473B7"
comment = "#7081d0"
dark5 = "#5866A2"
bright_cyan = "#39DDFD"
visual = "#76639e"
bg_visual = "#76639e"
cyan = "#04d1f9"
dark_cyan = "#10A1BD"
magenta = "#a48cf2"
magenta2 = "#bf4f8e"
magenta3 = "#722f55"
pink = "#f265b5"
purple = "#a48cf2"
orange = "#f7c67f"
yellow = "#f1fc79"
dark_yellow = "#c0c95f"
green = "#37f499"
bright_green = "#00FA82"
dark_green = "#33C57F"
red = "#f16c75"
bright_red = "#f0313e"

# Derived colors
bg_search = "#7081d0"
